### ISSUE TITLE
[Feat] 패키지 구조 잡기

### ISSUE THREAD

**Issue by geniusYoo** [NOW-SOPT-APP8-JUMPIT/Jumpit-SERVER#4]
## ☑️ 어떤 기능인가요?
패키지 구조 잡기 + 기본 세팅

## ☑️ TODO
- [x] 패키지 구조 도메인구조로 변환
- [x] DB 설계
- [x] Entity 클래스 정의
- [x] Repository 클래스 정의
- [x] Exception, JpaAuditingConfig, Message, Response 정의
